// Generated by Skyramp v1.3.13 on 2026-03-16 17:36:14.176783373 +0000 UTC m=+163.332584375
// Command: skyramp generate fuzz rest http://localhost:3001/api/auth/login \
// 		--api-schema /home/runner/work/new-project/new-project/openapi.yaml \
// 		--framework playwright \
// 		--language javascript \
// 		--method POST \
// 		--output auth_login_fuzz_test.spec.js \
// 		--output-dir /home/runner/work/new-project/new-project/tests \
// 		--overwrite \
// 		--provider \
// 		--request-data {"email":"user@shopeasy.com","password":"password123"} \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
const { SkyrampClient, getBaseUrl, getValue, iterate } = require('@skyramp/skyramp');
const { test } = require('@playwright/test');
const assert = require('assert');

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3001");

// fuzz test for /api/auth/login POST
test('testLoginPost', async () => {
    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const loginPostRequestBody = `{
            "email": "user@shopeasy.com",
            "password": "password123"
        }`
    
    // Fuzz strategies
    const loginPostFuzzedBody = {
        "email": "0123456789",
        "password": "0123456789"
    };
    // Fuzz status codes
    const expectedLoginPostStatusCode = {
        "email": "401",
        "password": "401"
    };
    // Fuzz status codes for Null values
    const expectedLoginPostNullStatusCode = {
        "email": "401",
        "password": "401"
    };

    // Execute Request
    let loginPostResponse = await client.sendRequest({
        url:URL,
        path:"/api/auth/login",
        method:"POST",
        body:loginPostRequestBody,
        headers:headers,
        expectedCode:"20x"
    });


    for (const key of iterate(loginPostFuzzedBody)) {
        // Execute Request
        loginPostResponse = await client.sendRequest({
            url:URL,
            path:"/api/auth/login",
            method:"POST",
            body:loginPostRequestBody,
            headers:headers,
            dataOverride:{[key]: getValue(loginPostFuzzedBody, key)},
            expectedCode:getValue(expectedLoginPostStatusCode, key),
            description:`Fuzzing request body ${key} to ${getValue(loginPostFuzzedBody, key)}`
        });


        // Execute Request
        loginPostResponse = await client.sendRequest({
            url:URL,
            path:"/api/auth/login",
            method:"POST",
            body:loginPostRequestBody,
            headers:headers,
            dataOverride:{[key]: null},
            expectedCode:getValue(expectedLoginPostNullStatusCode, key),
            description:`Fuzzing request body ${key} to null`
        });
    }


    assert.ok(client.isSuccess(), JSON.stringify(client.getFailedResponses()))
});

