// Generated by Skyramp v1.3.13 on 2026-03-16 18:42:59.184664588 +0000 UTC m=+239.266771973
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language javascript \
// 		--output auth_login_orders_access_integration_test.spec.js \
// 		--output-dir /home/runner/work/new-project/new-project/tests \
// 		--overwrite \
// 		--provider \
// 		--runtime local \
// 		--skipProvisionParents \
// 		--trace /home/runner/work/new-project/new-project/tests/scenario_auth-login-orders-access.json

// Import of required libraries
const { SkyrampClient, getBaseUrl, getValue } = require('@skyramp/skyramp');
const { test } = require('@playwright/test');
const assert = require('assert');

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3001");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const loginPostRequestBody = `{
            "email": "admin@shopeasy.com",
            "password": "password123"
        }`
    
    // Execute Request
    let loginPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/auth/login",
        method:"POST",
        body:loginPostRequestBody,
        headers:headers
    });

    // Generated Assertions
    assert.strictEqual(loginPostResponse.statusCode, 200, 'status code');

    // Execute Request
    let ordersGetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/orders",
        method:"GET",
        headers:headers
    });

    // Generated Assertions
    assert.strictEqual(ordersGetResponse.statusCode, 200, 'status code');
});

