// Generated by Skyramp v1.3.13 on 2026-03-16 18:42:59.267964431 +0000 UTC m=+239.350071819
// Command: skyramp generate fuzz rest http://localhost:3001/api/auth/logout \
// 		--api-schema /home/runner/work/new-project/new-project/openapi.yaml \
// 		--framework playwright \
// 		--language javascript \
// 		--method POST \
// 		--output auth_logout_fuzz_test.spec.js \
// 		--output-dir /home/runner/work/new-project/new-project/tests \
// 		--overwrite \
// 		--provider \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
const { SkyrampClient, getBaseUrl, getValue, iterate } = require('@skyramp/skyramp');
const { test } = require('@playwright/test');
const assert = require('assert');

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3001");

// fuzz test for /api/auth/logout POST
test('testLogoutPost', async () => {
    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    let logoutPostResponse = await client.sendRequest({
        url:URL,
        path:"/api/auth/logout",
        method:"POST",
        headers:headers,
        expectedCode:"20x"
    });


    assert.ok(client.isSuccess(), JSON.stringify(client.getFailedResponses()))
});

