// Generated by Skyramp v1.3.13 on 2026-03-16 20:27:20.980618098 +0000 UTC m=+328.244699485
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language javascript \
// 		--output auth_login_logout_integration_test.spec.js \
// 		--output-dir /home/runner/work/new-project/new-project/tests \
// 		--overwrite \
// 		--provider \
// 		--runtime local \
// 		--skipProvisionParents \
// 		--trace /home/runner/work/new-project/new-project/tests/scenario_auth-login-logout.json

// Import of required libraries
const { SkyrampClient, getBaseUrl, getValue } = require('@skyramp/skyramp');
const { test } = require('@playwright/test');
const assert = require('assert');

// URL for test requests
let URL_new_project_git_nk_testbot_nkumar0101s_projects = getBaseUrl("SKYRAMP_TEST_BASE_URL", "https://new-project-git-nk-testbot-nkumar0101s-projects.vercel.app");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const loginPostRequestBody = `{
            "email": "user@shopeasy.com",
            "password": "password123"
        }`
    
    // Execute Request
    let loginPostResponse = await client.sendRequest({
        url:URL_new_project_git_nk_testbot_nkumar0101s_projects,
        path:"/api/auth/login",
        method:"POST",
        body:loginPostRequestBody,
        headers:headers
    });

    // Generated Assertions
    assert.strictEqual(loginPostResponse.statusCode, 200, 'status code');

    // Request Body
    const logoutPostRequestBody = `{}`
    
    // Execute Request
    let logoutPostResponse = await client.sendRequest({
        url:URL_new_project_git_nk_testbot_nkumar0101s_projects,
        path:"/api/auth/logout",
        method:"POST",
        body:logoutPostRequestBody,
        headers:headers
    });

    // Generated Assertions
    assert.strictEqual(logoutPostResponse.statusCode, 200, 'status code');
});

