// Generated by Skyramp v1.3.13 on 2026-03-16 20:27:21.09016465 +0000 UTC m=+328.354246037
// Command: skyramp generate contract rest https://new-project-git-nk-testbot-nkumar0101s-projects.vercel.app/api/auth/login \
// 		--api-schema /home/runner/work/new-project/new-project/openapi.yaml \
// 		--framework playwright \
// 		--language javascript \
// 		--method POST \
// 		--output auth_login_contract_test_v2.spec.js \
// 		--output-dir /home/runner/work/new-project/new-project/tests \
// 		--overwrite \
// 		--provider \
// 		--request-data {"email":"admin@shopeasy.com","password":"password123"} \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
const { SkyrampClient, checkSchema, getBaseUrl, getResponseValue } = require('@skyramp/skyramp');
const { test } = require('@playwright/test');
const assert = require('assert');

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "https://new-project-git-nk-testbot-nkumar0101s-projects.vercel.app");

// contract test for /api/auth/login POST
test('testLoginPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const loginPostRequestBody = `{
        "email": "admin@shopeasy.com",
        "password": "password123"
    }`;

    // Expected Response Body
    const expectedLoginPostResponseBody = `{
        "token": "string",
        "user": {
            "email": "string",
            "id": "string",
            "name": "string",
            "role": "string"
        }
    }`;

    // Execute Request
    const loginPostResponse = await client.sendRequest({
        url: URL,
        path: "/api/auth/login",
        method: "POST",
        body: loginPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    assert.strictEqual(loginPostResponse.statusCode, 200, 'status code');
    assert.ok(checkSchema(loginPostResponse, expectedLoginPostResponseBody), 'schema should match');
    assert.notStrictEqual(getResponseValue(loginPostResponse, "token"), null, 'value should not be null');
    assert.notStrictEqual(getResponseValue(loginPostResponse, "user.email"), null, 'value should not be null');
    assert.notStrictEqual(getResponseValue(loginPostResponse, "user.id"), null, 'value should not be null');
});
