// Generated by Skyramp v1.3.13 on 2026-03-16 17:36:39.579411027 +0000 UTC m=+188.735212019
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language javascript \
// 		--output auth_login_access_flow_integration_test.spec.js \
// 		--output-dir /home/runner/work/new-project/new-project/tests \
// 		--overwrite \
// 		--provider \
// 		--runtime local \
// 		--skipProvisionParents \
// 		--trace /home/runner/work/new-project/new-project/tests/scenario_auth-login-access-flow.json

// Import of required libraries
const { SkyrampClient, getBaseUrl, getValue } = require('@skyramp/skyramp');
const { test } = require('@playwright/test');
const assert = require('assert');

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3001");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const loginPostRequestBody = `{
            "email": "user@shopeasy.com",
            "password": "password123"
        }`
    
    // Execute Request
    let loginPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/auth/login",
        method:"POST",
        body:loginPostRequestBody,
        headers:headers
    });

    // Generated Assertions
    assert.strictEqual(loginPostResponse.statusCode, 200, 'status code');

    // Execute Request
    let productsGetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/products",
        method:"GET",
        headers:headers
    });

    // Generated Assertions
    assert.strictEqual(productsGetResponse.statusCode, 200, 'status code');
});

