// Generated by Skyramp v1.3.13 on 2026-03-16 20:27:21.189492715 +0000 UTC m=+328.453574092
// Command: skyramp generate contract rest https://new-project-git-nk-testbot-nkumar0101s-projects.vercel.app/api/auth/logout \
// 		--api-schema /home/runner/work/new-project/new-project/openapi.yaml \
// 		--framework playwright \
// 		--language javascript \
// 		--method POST \
// 		--output auth_logout_contract_test_v2.spec.js \
// 		--output-dir /home/runner/work/new-project/new-project/tests \
// 		--overwrite \
// 		--provider \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
const { SkyrampClient, getBaseUrl } = require('@skyramp/skyramp');
const { test } = require('@playwright/test');
const assert = require('assert');

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "https://new-project-git-nk-testbot-nkumar0101s-projects.vercel.app");

// contract test for /api/auth/logout POST
test('testLogoutPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    const logoutPostResponse = await client.sendRequest({
        url: URL,
        path: "/api/auth/logout",
        method: "POST",
        headers: headers
    });

    // Generated Assertions
    assert.strictEqual(logoutPostResponse.statusCode, 200, 'status code');
});
