// Generated by Skyramp v1.3.11 on 2026-03-05 19:40:46.87388176 +0000 UTC m=+156.827427998
// Command: skyramp generate contract rest https://new-project-azure-five.vercel.app/api/checkout \
// 		--api-schema /home/runner/work/new-project/new-project/openapi.yaml \
// 		--framework playwright \
// 		--language javascript \
// 		--output-dir /home/runner/work/new-project/new-project/tests \
// 		--overwrite \
// 		--runtime local

// Import of required libraries
const { SkyrampClient, checkSchema, getResponseValue } = require('@skyramp/skyramp');
const { test } = require('@playwright/test');
const assert = require('assert');

// URL for test requests
let URL = "https://new-project-azure-five.vercel.app";

// contract test for /api/checkout POST
test('testCheckoutPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Fetch a real product ID from the live server
    const productsResponse = await client.sendRequest({
        url: URL,
        path: "/api/products",
        method: "GET",
        headers: headers
    });
    assert.strictEqual(productsResponse.statusCode, 200, 'products status code');
    const realProductId = getResponseValue(productsResponse, "0.id");

    // Request Body
    const checkoutPostRequestBody = `{
        "customer": {
            "address": "123 Main St, New York 10001",
            "email": "jane@example.com",
            "name": "Jane Smith"
        },
        "items": [
            {
                "productId": "697e5563-5eed-45db-be7c-b543a102641b",
                "quantity": 1
            }
        ],
        "paymentMethod": "credit_card"
    }`;

    // Expected Response Body
    const expectedCheckoutPostResponseBody = `{
        "createdAt": "2026-03-05T12:00:00.000Z",
        "customer": {
            "address": "123 Main St, New York 10001",
            "email": "jane@example.com",
            "name": "Jane Smith"
        },
        "id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
        "items": [
            {
                "name": "Wireless Headphones",
                "price": 79.99,
                "productId": "c70b4c2b-5b43-4de3-a423-7cec36228416",
                "quantity": 1,
                "subtotal": 79.99
            }
        ],
        "paymentMethod": "credit_card",
        "paymentStatus": "success",
        "status": "confirmed",
        "total": 79.99
    }`;

    // Execute Request
    const checkoutPostResponse = await client.sendRequest({
        url: URL,
        path: "/api/checkout",
        method: "POST",
        body: checkoutPostRequestBody,
        headers: headers,
        dataOverride: {
            "items": [{ "productId": realProductId, "quantity": 1 }]
        }
    });

    // Generated Assertions
    assert.strictEqual(checkoutPostResponse.statusCode, 201, 'status code');
    assert.ok(checkSchema(checkoutPostResponse, expectedCheckoutPostResponseBody), 'schema should match');
    assert.notStrictEqual(getResponseValue(checkoutPostResponse, "createdAt"), null, 'value should not be null');
    assert.notStrictEqual(getResponseValue(checkoutPostResponse, "customer.address"), null, 'value should not be null');
    assert.notStrictEqual(getResponseValue(checkoutPostResponse, "customer.email"), null, 'value should not be null');
});
