// Generated by Skyramp v1.3.11 on 2026-03-05 19:12:41.439213411 +0000 UTC m=+151.835219177
// Command: skyramp generate fuzz rest http://localhost:3001/api/checkout \
// 		--framework playwright \
// 		--language javascript \
// 		--method POST \
// 		--output-dir /home/runner/work/new-project/new-project/tests \
// 		--overwrite \
// 		--request-data {"items":[{"productId":"test-id","quantity":1}],"customer":{"name":"Test User","email":"test@example.com"},"paymentMethod":"credit_card"} \
// 		--runtime local

// Import of required libraries
const { SkyrampClient, getValue, iterate } = require('@skyramp/skyramp');
const { test } = require('@playwright/test');
const assert = require('assert');

// URL for test requests
let URL = "http://localhost:3001";

// fuzz test for /api/checkout POST
test('testCheckoutPost', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Step 0: fetch a valid product ID to use in the checkout request
    const productsResponse = await client.sendRequest({
        url: URL,
        path: "/api/products",
        method: "GET",
        headers: headers,
        expectedCode: "20x"
    });
    const productId = JSON.parse(productsResponse.responseBody)[0].id;

    // Request Body
    const checkoutPostRequestBody = JSON.stringify({
        "items": [{ "productId": productId, "quantity": 1 }],
        "customer": { "name": "Test User", "email": "test@example.com" },
        "paymentMethod": "credit_card"
    });

    // Fuzz strategies
    const checkoutPostFuzzedBody = {
        "customer": {
            "email": "0123456789",
            "name": "0123456789"
        },
        "items": [{
            "productId": "0123456789",
            "quantity": -10
        }],
        "paymentMethod": "0123456789"
    };
    // Fuzz status codes:
    // - customer object with valid strings → 20x (any string is accepted for name/email)
    // - items.productId with invalid ID → 40x (product not found)
    // - items.quantity with -10 → 20x (no quantity validation, negative allowed)
    // - paymentMethod with any string → 20x (no validation on payment method value)
    const expectedCheckoutPostStatusCode = {
        "customer": {
            "email": "20x",
            "name": "20x"
        },
        "items": [{
            "productId": "40x",
            "quantity": "20x"
        }],
        "paymentMethod": "20x"
    };
    // Fuzz status codes for Null values:
    // - customer null → 40x (required)
    // - items null → 40x (cart is empty)
    // - items.quantity null → 20x (backend computes subtotal as 0, no validation)
    // - paymentMethod null → 20x (optional, defaults to credit_card)
    const expectedCheckoutPostNullStatusCode = {
        "customer": {
            "email": "40x",
            "name": "40x"
        },
        "items": [{
            "productId": "40x",
            "quantity": "20x"
        }],
        "paymentMethod": "20x"
    };

    // Execute Request
    let checkoutPostResponse = await client.sendRequest({
        url:URL,
        path:"/api/checkout",
        method:"POST",
        body:checkoutPostRequestBody,
        headers:{ ...headers, "Content-Type": "application/json" },
        expectedCode:"20x"
    });


    for (const key of iterate(checkoutPostFuzzedBody)) {
        // Execute Request
        checkoutPostResponse = await client.sendRequest({
            url:URL,
            path:"/api/checkout",
            method:"POST",
            body:checkoutPostRequestBody,
            headers:{ ...headers, "Content-Type": "application/json" },
            dataOverride:{[key]: getValue(checkoutPostFuzzedBody, key)},
            expectedCode:getValue(expectedCheckoutPostStatusCode, key),
            description:`Fuzzing request body ${key} to ${getValue(checkoutPostFuzzedBody, key)}`
        });


        // Execute Request
        checkoutPostResponse = await client.sendRequest({
            url:URL,
            path:"/api/checkout",
            method:"POST",
            body:checkoutPostRequestBody,
            headers:{ ...headers, "Content-Type": "application/json" },
            dataOverride:{[key]: null},
            expectedCode:getValue(expectedCheckoutPostNullStatusCode, key),
            description:`Fuzzing request body ${key} to null`
        });
    }


    assert.ok(client.isSuccess(), JSON.stringify(client.getFailedResponses()))
});
