// Generated by Skyramp v1.3.11 on 2026-03-06 23:31:30.933945592 +0000 UTC m=+121.404129624
// Command: skyramp generate smoke rest http://localhost:3001/api/checkout \
// 		--api-schema /home/runner/work/new-project/new-project/openapi.yaml \
// 		--framework playwright \
// 		--language javascript \
// 		--method POST \
// 		--output checkout_smoke_test.spec.js \
// 		--output-dir /home/runner/work/new-project/new-project/tests \
// 		--overwrite \
// 		--runtime local

// Import of required libraries
const { SkyrampClient } = require('@skyramp/skyramp');
const { test } = require('@playwright/test');
const assert = require('assert');

// URL for test requests
let URL = "http://localhost:3001";

// smoke test for /api/checkout POST
test('testCheckoutPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const checkoutPostRequestBody = `{
        "customer": {
            "address": "123 Main St, New York 10001",
            "email": "jane@example.com",
            "name": "Jane Smith"
        },
        "items": [
            {
                "productId": "697e5563-5eed-45db-be7c-b543a102641b",
                "quantity": 2
            }
        ],
        "paymentMethod": "credit_card"
    }`;

    // Execute Request
    const checkoutPostResponse = await client.sendRequest({
        url: URL,
        path: "/api/checkout",
        method: "POST",
        body: checkoutPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    assert.strictEqual(checkoutPostResponse.statusCode, 201, 'status code');
});
