// Generated by Skyramp v1.3.11 on 2026-03-10 19:31:50.878523347 +0000 UTC m=+169.522411340
// Command: skyramp generate fuzz rest http://localhost:3001/api/checkout \
// 		--api-schema /home/runner/work/new-project/new-project/openapi.yaml \
// 		--framework playwright \
// 		--language javascript \
// 		--method POST \
// 		--output checkout_discount_fuzz_test.spec.js \
// 		--output-dir /home/runner/work/new-project/new-project/tests \
// 		--overwrite \
// 		--request-data {"customer":{"name":"Jane Smith","email":"jane@example.com","address":"123 Main St, New York 10001"},"paymentMethod":"credit_card","discountCode":"SAVE10","items":[{"productId":"a1000000-0000-0000-0000-000000000001","quantity":1}]} \
// 		--runtime local

// Import of required libraries
const { SkyrampClient, getValue, iterate } = require('@skyramp/skyramp');
const { test } = require('@playwright/test');
const assert = require('assert');

// URL for test requests
let URL = "http://localhost:3001";

// fuzz test for /api/checkout POST
test('testCheckoutPost', async () => {
    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const checkoutPostRequestBody = `{
            "customer": {
                "name": "Jane Smith",
                "email": "jane@example.com",
                "address": "123 Main St, New York 10001"
            },
            "paymentMethod": "credit_card",
            "discountCode": "SAVE10",
            "items": [
                {
                    "productId": "a1000000-0000-0000-0000-000000000001",
                    "quantity": 1
                }
            ]
        }`
    
    // Fuzz strategies
    const checkoutPostFuzzedBody = {
        "customer": {
            "address": "0123456789",
            "email": "0123456789",
            "name": "0123456789"
        },
        "discountCode": "0123456789",
        "items": [{
            "productId": "0123456789",
            "quantity": -10
        }],
        "paymentMethod": "0123456789"
    };
    // Fuzz status codes
    const expectedCheckoutPostStatusCode = {
        "customer": {
            "address": "400",
            "email": "400",
            "name": "400"
        },
        "discountCode": "400",
        "items": [{
            "productId": "400",
            "quantity": "400"
        }],
        "paymentMethod": "400"
    };
    // Fuzz status codes for Null values
    const expectedCheckoutPostNullStatusCode = {
        "customer": {
            "address": "400",
            "email": "400",
            "name": "400"
        },
        "discountCode": "400",
        "items": [{
            "productId": "400",
            "quantity": "400"
        }],
        "paymentMethod": "400"
    };

    // Execute Request
    let checkoutPostResponse = await client.sendRequest({
        url:URL,
        path:"/api/checkout",
        method:"POST",
        body:checkoutPostRequestBody,
        headers:headers,
        expectedCode:"20x"
    });


    for (const key of iterate(checkoutPostFuzzedBody)) {
        // Execute Request
        checkoutPostResponse = await client.sendRequest({
            url:URL,
            path:"/api/checkout",
            method:"POST",
            body:checkoutPostRequestBody,
            headers:headers,
            dataOverride:{[key]: getValue(checkoutPostFuzzedBody, key)},
            expectedCode:getValue(expectedCheckoutPostStatusCode, key),
            description:`Fuzzing request body ${key} to ${getValue(checkoutPostFuzzedBody, key)}`
        });


        // Execute Request
        checkoutPostResponse = await client.sendRequest({
            url:URL,
            path:"/api/checkout",
            method:"POST",
            body:checkoutPostRequestBody,
            headers:headers,
            dataOverride:{[key]: null},
            expectedCode:getValue(expectedCheckoutPostNullStatusCode, key),
            description:`Fuzzing request body ${key} to null`
        });
    }


    assert.ok(client.isSuccess(), JSON.stringify(client.getFailedResponses()))
});

