// Generated by Skyramp v1.3.11 on 2026-03-06 23:59:12.135425118 +0000 UTC m=+127.264096721
// Command: skyramp generate fuzz rest http://localhost:3001/api/checkout \
// 		--api-schema /home/runner/work/new-project/new-project/openapi.yaml \
// 		--framework playwright \
// 		--language javascript \
// 		--method POST \
// 		--output checkout_fuzz_test.spec.js \
// 		--output-dir /home/runner/work/new-project/new-project/tests \
// 		--overwrite \
// 		--runtime local

// Import of required libraries
const { SkyrampClient, getValue, iterate } = require('@skyramp/skyramp');
const { test } = require('@playwright/test');
const assert = require('assert');

// URL for test requests
let URL = "http://localhost:3001";

// fuzz test for /api/checkout POST
test('testCheckoutPost', async () => {
    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const checkoutPostRequestBody = `{
            "customer": {
                "address": "123 Main St, New York 10001",
                "email": "jane@example.com",
                "name": "Jane Smith"
            },
            "items": [
                {
                    "productId": "697e5563-5eed-45db-be7c-b543a102641b",
                    "quantity": 2
                }
            ],
            "paymentMethod": "credit_card"
        }`
    
    // Fuzz strategies
    const checkoutPostFuzzedBody = {
        "customer": {
            "address": "123 Main St, New York 10001",
            "email": "jane@example.com",
            "name": "Jane Smith"
        },
        "items": [{
            "productId": "697e5563-5eed-45db-be7c-b543a102641b",
            "quantity": 2
        }],
        "paymentMethod": "credit_card"
    };
    // Fuzz status codes
    const expectedCheckoutPostStatusCode = {
        "customer": {
            "address": "400",
            "email": "400",
            "name": "400"
        },
        "items": [{
            "productId": "400",
            "quantity": "400"
        }],
        "paymentMethod": "400"
    };
    // Fuzz status codes for Null values
    const expectedCheckoutPostNullStatusCode = {
        "customer": {
            "address": "400",
            "email": "400",
            "name": "400"
        },
        "items": [{
            "productId": "400",
            "quantity": "400"
        }],
        "paymentMethod": "400"
    };

    // Execute Request
    let checkoutPostResponse = await client.sendRequest({
        url:URL,
        path:"/api/checkout",
        method:"POST",
        body:checkoutPostRequestBody,
        headers:headers,
        expectedCode:"20x"
    });


    for (const key of iterate(checkoutPostFuzzedBody)) {
        // Execute Request
        checkoutPostResponse = await client.sendRequest({
            url:URL,
            path:"/api/checkout",
            method:"POST",
            body:checkoutPostRequestBody,
            headers:headers,
            dataOverride:{[key]: getValue(checkoutPostFuzzedBody, key)},
            expectedCode:getValue(expectedCheckoutPostStatusCode, key),
            description:`Fuzzing request body ${key} to ${getValue(checkoutPostFuzzedBody, key)}`
        });


        // Execute Request
        checkoutPostResponse = await client.sendRequest({
            url:URL,
            path:"/api/checkout",
            method:"POST",
            body:checkoutPostRequestBody,
            headers:headers,
            dataOverride:{[key]: null},
            expectedCode:getValue(expectedCheckoutPostNullStatusCode, key),
            description:`Fuzzing request body ${key} to null`
        });
    }


    assert.ok(client.isSuccess(), JSON.stringify(client.getFailedResponses()))
});

