// Generated by Skyramp v1.3.11 on 2026-03-06 23:31:49.428153232 +0000 UTC m=+139.898337254
// Command: skyramp generate load rest http://localhost:3001/api/checkout \
// 		--api-schema /home/runner/work/new-project/new-project/openapi.yaml \
// 		--default-duration 5 \
// 		--default-num-threads 1 \
// 		--framework playwright \
// 		--language javascript \
// 		--method POST \
// 		--output checkout_load_test.spec.js \
// 		--output-dir /home/runner/work/new-project/new-project/tests \
// 		--overwrite \
// 		--runtime local

// Import of required libraries
const { SkyrampClient } = require('@skyramp/skyramp');
const { AsyncScenario, LoadTestConfig } = require('@skyramp/skyramp');const { test } = require('@playwright/test');
const assert = require('assert');

// URL for test requests
let URL = "http://localhost:3001";

let loadTestConfig = new LoadTestConfig({
    loadDuration: 5,
    loadNumThreads: 1
});

test('testCheckoutPost', async () => {
    test.setTimeout(35000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    const scenario = new AsyncScenario({name: "scenario"});
    // Request Body
    const checkoutPostRequestBody = `{
            "customer": {
                "address": "123 Main St, New York 10001",
                "email": "jane@example.com",
                "name": "Jane Smith"
            },
            "items": [
                {
                    "productId": "697e5563-5eed-45db-be7c-b543a102641b",
                    "quantity": 2
                }
            ],
            "paymentMethod": "credit_card"
        }`
    
    // Add Request to Scenario
    let checkoutPostResponse = scenario.addAsyncRequest({
        name: "checkout_POST",
        url: URL,
        path: "/api/checkout",
        method: "POST",
        body: checkoutPostRequestBody,
        headers: headers,
        expectedCode: "201"
    });

    const result = await client.sendScenario(scenario, {
            loadTestConfig: loadTestConfig
        });

    const overallStatus = await result.getOverallStatus();
    console.log(JSON.stringify({ "result": overallStatus }, null, 2));
});

