// Generated by Skyramp v1.3.11 on 2026-03-10 19:31:50.593481822 +0000 UTC m=+169.237369804
// Command: skyramp generate contract rest http://localhost:3001/api/checkout \
// 		--api-schema /home/runner/work/new-project/new-project/openapi.yaml \
// 		--framework playwright \
// 		--language javascript \
// 		--method POST \
// 		--output checkout_discount_contract_test.spec.js \
// 		--output-dir /home/runner/work/new-project/new-project/tests \
// 		--overwrite \
// 		--request-data {"customer":{"name":"Jane Smith","email":"jane@example.com","address":"123 Main St, New York 10001"},"paymentMethod":"credit_card","discountCode":"FLAT5","items":[{"productId":"a1000000-0000-0000-0000-000000000001","quantity":1}]} \
// 		--runtime local

// Import of required libraries
const { SkyrampClient, checkSchema, getResponseValue } = require('@skyramp/skyramp');
const { test } = require('@playwright/test');
const assert = require('assert');

// URL for test requests
let URL = "http://localhost:3001";

// contract test for /api/checkout POST
test('testCheckoutPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const checkoutPostRequestBody = `{
        "customer": {
            "address": "123 Main St, New York 10001",
            "email": "jane@example.com",
            "name": "Jane Smith"
        },
        "discountCode": "FLAT5",
        "items": [
            {
                "productId": "a1000000-0000-0000-0000-000000000001",
                "quantity": 1
            }
        ],
        "paymentMethod": "credit_card"
    }`;

    // Expected Response Body
    const expectedCheckoutPostResponseBody = `{
        "createdAt": "2026-03-05T12:00:00.000Z",
        "customer": {
            "address": "123 Main St, New York 10001",
            "email": "jane@example.com",
            "name": "Jane Smith"
        },
        "discountAmount": 16,
        "discountCode": "SAVE10",
        "id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
        "items": [
            {
                "name": "Wireless Headphones",
                "price": 79.99,
                "productId": "d76ed68c-ab06-4d0c-967a-dd80e6d1f247",
                "quantity": 2,
                "subtotal": 159.98
            }
        ],
        "paymentMethod": "credit_card",
        "paymentStatus": "success",
        "status": "confirmed",
        "subtotal": 159.98,
        "total": 143.98
    }`;

    // Execute Request
    const checkoutPostResponse = await client.sendRequest({
        url: URL,
        path: "/api/checkout",
        method: "POST",
        body: checkoutPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    assert.strictEqual(checkoutPostResponse.statusCode, 201, 'status code');
    assert.ok(checkSchema(checkoutPostResponse, expectedCheckoutPostResponseBody), 'schema should match');
    assert.notStrictEqual(getResponseValue(checkoutPostResponse, "createdAt"), null, 'value should not be null');
    assert.notStrictEqual(getResponseValue(checkoutPostResponse, "customer.address"), null, 'value should not be null');
    assert.notStrictEqual(getResponseValue(checkoutPostResponse, "customer.email"), null, 'value should not be null');
});
