// Generated by Skyramp v1.3.11 on 2026-03-05 19:12:41.439213411 +0000 UTC m=+151.835219177
// Command: skyramp generate fuzz rest http://localhost:3001/api/checkout \
// 		--framework playwright \
// 		--language javascript \
// 		--method POST \
// 		--output-dir /home/runner/work/new-project/new-project/tests \
// 		--overwrite \
// 		--request-data {"items":[{"productId":"test-id","quantity":1}],"customer":{"name":"Test User","email":"test@example.com"},"paymentMethod":"credit_card"} \
// 		--runtime local

// Import of required libraries
const { SkyrampClient, getValue, iterate } = require('@skyramp/skyramp');
const { test } = require('@playwright/test');
const assert = require('assert');

// URL for test requests
let URL = "http://localhost:3001";

// fuzz test for /api/checkout POST
test('testCheckoutPost', async () => {
    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const checkoutPostRequestBody = `{
            "items": [
                {
                    "productId": "test-id",
                    "quantity": 1
                }
            ],
            "customer": {
                "name": "Test User",
                "email": "test@example.com"
            },
            "paymentMethod": "credit_card"
        }`
    
    // Fuzz strategies
    const checkoutPostFuzzedBody = {
        "customer": {
            "email": "0123456789",
            "name": "0123456789"
        },
        "items": [{
            "productId": "0123456789",
            "quantity": -10
        }],
        "paymentMethod": "0123456789"
    };
    // Fuzz status codes
    const expectedCheckoutPostStatusCode = {
        "customer": {
            "email": "40x",
            "name": "40x"
        },
        "items": [{
            "productId": "40x",
            "quantity": "40x"
        }],
        "paymentMethod": "40x"
    };
    // Fuzz status codes for Null values
    const expectedCheckoutPostNullStatusCode = {
        "customer": {
            "email": "40x",
            "name": "40x"
        },
        "items": [{
            "productId": "40x",
            "quantity": "40x"
        }],
        "paymentMethod": "40x"
    };

    // Execute Request
    let checkoutPostResponse = await client.sendRequest({
        url:URL,
        path:"/api/checkout",
        method:"POST",
        body:checkoutPostRequestBody,
        headers:headers,
        expectedCode:"20x"
    });


    for (const key of iterate(checkoutPostFuzzedBody)) {
        // Execute Request
        checkoutPostResponse = await client.sendRequest({
            url:URL,
            path:"/api/checkout",
            method:"POST",
            body:checkoutPostRequestBody,
            headers:headers,
            dataOverride:{[key]: getValue(checkoutPostFuzzedBody, key)},
            expectedCode:getValue(expectedCheckoutPostStatusCode, key),
            description:`Fuzzing request body ${key} to ${getValue(checkoutPostFuzzedBody, key)}`
        });


        // Execute Request
        checkoutPostResponse = await client.sendRequest({
            url:URL,
            path:"/api/checkout",
            method:"POST",
            body:checkoutPostRequestBody,
            headers:headers,
            dataOverride:{[key]: null},
            expectedCode:getValue(expectedCheckoutPostNullStatusCode, key),
            description:`Fuzzing request body ${key} to null`
        });
    }


    assert.ok(client.isSuccess(), JSON.stringify(client.getFailedResponses()))
});

