// Generated by Skyramp v1.3.11 on 2026-03-06 23:31:30.797581722 +0000 UTC m=+121.267765764
// Command: skyramp generate e2e rest \
// 		--framework playwright \
// 		--language javascript \
// 		--output checkout_e2e_test.spec.js \
// 		--output-dir /home/runner/work/new-project/new-project/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/new-project/new-project/tests/skyramp_playwright.zip \
// 		--runtime local \
// 		--trace /home/runner/work/new-project/new-project/tests/skyramp_traces.json

// Import of required libraries
const { expect, getValue, newSkyrampPlaywrightPage } = require('@skyramp/skyramp');
const { test } = require('@playwright/test');
const assert = require('assert');

const pageTimeout = 15000;

test.use({
    storageState: '/home/runner/work/new-project/new-project/tests/skyramp_session_storage.json',
});

test('testE2E', async ({ page }) => {
    test.setTimeout(126000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("https://new-project-git-nk-testbot-nkumar0101s-projects.vercel.app/");
    await page.getByTestId("add-to-cart-btn-wireless-headphones").click();
    await page.getByTestId("delete-product-btn-coffee-maker").click();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/products/**");
    await page.getByTestId("delete-confirm-ok").click();
    const response0 = await responsePromise0;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByTestId("add-to-cart-btn-yoga-mat").click();
    await page.getByTestId("nav-cart").click();
    await page.getByTestId("proceed-to-checkout-btn").click();
    await page.getByTestId("checkout-name").click();

    const playwrightRequest0 = {"customer": {
            "email": "nk@skyramp.dev",
            "name": "NK"
        }};

    await page.getByTestId("checkout-name").fill(getValue(playwrightRequest0, "customer.name"));
    await page.getByTestId("checkout-email").click();
    await page.getByTestId("checkout-email").fill(getValue(playwrightRequest0, "customer.email"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise1 = page.waitForResponse("**/api/checkout**");
    await page.getByTestId("place-order-btn").click();
    const response1 = await responsePromise1;

    await page.getByTestId("view-order-btn").click();
    await expect(page.getByTestId("order-detail-customer-email")).toContainText("nk@skyramp.dev");
});
