// Generated by Skyramp v1.3.11 on 2026-03-09 18:09:18.463822247 +0000 UTC m=+159.892010065
// Command: skyramp generate fuzz rest http://localhost:3001/api/discounts/validate/SAVE10 \
// 		--api-schema /home/runner/work/new-project/new-project/openapi.yaml \
// 		--framework playwright \
// 		--language javascript \
// 		--method GET \
// 		--output discounts_fuzz_test.spec.js \
// 		--output-dir /home/runner/work/new-project/new-project/tests \
// 		--overwrite \
// 		--runtime local

// Import of required libraries
const { SkyrampClient, getValue, iterate } = require('@skyramp/skyramp');
const { test } = require('@playwright/test');
const assert = require('assert');

// URL for test requests
let URL = "http://localhost:3001";

// fuzz test for /api/discounts/validate/SAVE10 GET
test('testSave10Get', async () => {
    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    let save10GetResponse = await client.sendRequest({
        url:URL,
        path:"/api/discounts/validate/SAVE10",
        method:"GET",
        headers:headers,
        expectedCode:"20x"
    });


    assert.ok(client.isSuccess(), JSON.stringify(client.getFailedResponses()))
});

