// Generated by Skyramp v1.3.11 on 2026-03-09 18:10:11.26800666 +0000 UTC m=+212.696194499
// Command: skyramp generate e2e rest \
// 		--framework playwright \
// 		--language javascript \
// 		--output discounts_e2e_test.spec.js \
// 		--output-dir /home/runner/work/new-project/new-project/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/new-project/new-project/tests/ui-flow.zip \
// 		--runtime local \
// 		--trace /home/runner/work/new-project/new-project/tests/skyramp_traces.json

// Import of required libraries
const { expect, getValue, newSkyrampPlaywrightPage } = require('@skyramp/skyramp');
const { test } = require('@playwright/test');
const assert = require('assert');

const pageTimeout = 15000;

test('testE2E', async ({ page }) => {
    test.setTimeout(180000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("https://new-project-git-nk-testbot-nkumar0101s-projects.vercel.app/");
    await page.getByTestId("reset-btn").click();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/reset**");
    await page.getByTestId("reset-confirm-ok").click();
    const response0 = await responsePromise0;

    await page.getByTestId("add-to-cart-btn-wireless-headphones").click();
    await page.getByTestId("edit-product-btn-running-shoes").click();
    await page.getByTestId("product-form-stock").click();

    const playwrightRequest0 = {"stock": 25};

    await page.getByTestId("product-form-stock").fill(getValue(playwrightRequest0, "stock").toString());
    await page.getByTestId("product-form-stock").press("Enter");
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise1 = page.waitForResponse("**/api/products/**");
    await page.getByTestId("product-form-submit").click();
    const response1 = await responsePromise1;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.getByTestId("product-stock-running-shoes")).toBeVisible();
    await expect(page.getByTestId("product-stock-running-shoes")).toContainText("25 in stock");
    await page.getByTestId("delete-product-btn-coffee-maker").click();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise2 = page.waitForResponse("**/api/products/**");
    await page.getByTestId("delete-confirm-ok").click();
    const response2 = await responsePromise2;

    await page.getByTestId("add-to-cart-btn-mechanical-keyboard").click();
    await page.getByTestId("add-to-cart-btn-blender").click();
    await page.getByTestId("nav-cart").click();
    await page.getByTestId("proceed-to-checkout-btn").click();
    await page.getByTestId("checkout-name").click();

    const playwrightRequest1 = {"customer": {
            "email": "nk@skyramp.dev",
            "name": "Nikhil Kumar"
        }};

    await page.getByTestId("checkout-name").fill(getValue(playwrightRequest1, "customer.name"));
    await page.getByTestId("checkout-name").click();
    await page.getByTestId("checkout-email").click();
    await page.getByTestId("checkout-email").fill(getValue(playwrightRequest1, "customer.email"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise3 = page.waitForResponse("**/api/checkout**");
    await page.getByTestId("place-order-btn").click();
    const response3 = await responsePromise3;

    await page.getByTestId("view-order-btn").click();
    await expect(page.getByTestId("order-detail-customer-email")).toContainText("nk@skyramp.dev");
});
