// Generated by Skyramp v1.3.13 on 2026-03-16 21:57:41.713692373 +0000 UTC m=+112.166283972
// Command: skyramp generate ui rest \
// 		--exclude clients2.google.com,accounts.google.com \
// 		--framework playwright \
// 		--language javascript \
// 		--output discount_ui_test.spec.js \
// 		--output-dir /home/runner/work/new-project/new-project/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/new-project/new-project/tests/discount.zip \
// 		--provider \
// 		--skipProvisionParents

// Import of required libraries
const { expect, getValue, newSkyrampPlaywrightPage } = require('@skyramp/skyramp');
const { test } = require('@playwright/test');
const assert = require('assert');

const pageTimeout = 15000;

test.use({
    storageState: '/Users/nkumar0101/Desktop/new-project/tests/skyramp_session_storage.json',
});

test('testUi', async ({ page }) => {
    test.setTimeout(173000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("https://new-project-git-nk-testbot-nkumar0101s-projects.vercel.app/");
    await page.getByTestId("demo-user-btn").click();
    await page.getByTestId("login-submit-btn").click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByTestId("add-to-cart-btn-wireless-headphones").click();
    await page.getByTestId("nav-cart").click();
    await page.getByTestId("proceed-to-checkout-btn").click();
    await page.getByTestId("discount-code-input").click();

    const playwrightRequest0 = {
        "customer": {
            "email": "nk@skyramp.dev",
            "name": "N K"
        },
        "discountCode": "SAVE10"
    };

    await page.getByTestId("discount-code-input").fill(getValue(playwrightRequest0, "discountCode"));
    await expect(page.getByTestId("review-total-amount")).toContainText("$79.99");
    await page.getByTestId("discount-apply-btn").click();
    await expect(page.getByTestId("review-total-amount")).toContainText("$71.99");
    await page.getByTestId("checkout-name").click();
    await page.getByTestId("checkout-name").fill(getValue(playwrightRequest0, "customer.name"));
    await page.getByTestId("checkout-email").click();
    await page.getByTestId("checkout-email").fill(getValue(playwrightRequest0, "customer.email"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/checkout**");
    await page.getByTestId("place-order-btn").click();
    const response0 = await responsePromise0;

    await page.getByTestId("view-order-btn").click();
    await expect(page.getByTestId("order-detail-total")).toContainText("$71.99");
});
