// Generated by Skyramp v1.3.11 on 2026-03-09 18:08:55.538080833 +0000 UTC m=+136.966268641
// Command: skyramp generate contract rest http://localhost:3001/api/discounts/validate/SAVE10 \
// 		--api-schema /home/runner/work/new-project/new-project/openapi.yaml \
// 		--framework playwright \
// 		--language javascript \
// 		--method GET \
// 		--output discounts_contract_test.spec.js \
// 		--output-dir /home/runner/work/new-project/new-project/tests \
// 		--overwrite \
// 		--runtime local

// Import of required libraries
const { SkyrampClient, checkSchema, getResponseValue } = require('@skyramp/skyramp');
const { test } = require('@playwright/test');
const assert = require('assert');

// URL for test requests
let URL = "http://localhost:3001";

// contract test for /api/discounts/validate/SAVE10 GET
test('testSave10Get', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Expected Response Body
    const expectedSave10GetResponseBody = `{
        "code": "SAVE10",
        "description": "10% off your order",
        "type": "percent",
        "value": 10
    }`;

    // Execute Request
    const save10GetResponse = await client.sendRequest({
        url: URL,
        path: "/api/discounts/validate/SAVE10",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    assert.strictEqual(save10GetResponse.statusCode, 200, 'status code');
    assert.ok(checkSchema(save10GetResponse, expectedSave10GetResponseBody), 'schema should match');
    assert.notStrictEqual(getResponseValue(save10GetResponse, "code"), null, 'value should not be null');
    assert.notStrictEqual(getResponseValue(save10GetResponse, "description"), null, 'value should not be null');
    assert.notStrictEqual(getResponseValue(save10GetResponse, "type"), null, 'value should not be null');
});
