// Generated by Skyramp v1.3.11 on 2026-03-09 18:09:16.595030962 +0000 UTC m=+158.023218790
// Command: skyramp generate integration rest http://localhost:3001/api/checkout \
// 		--api-schema /home/runner/work/new-project/new-project/openapi.yaml \
// 		--framework playwright \
// 		--language javascript \
// 		--output discounts_checkout_integration_test.spec.js \
// 		--output-dir /home/runner/work/new-project/new-project/tests \
// 		--overwrite \
// 		--runtime local

// Import of required libraries
const { SkyrampClient, getValue } = require('@skyramp/skyramp');
const { test } = require('@playwright/test');
const assert = require('assert');

// URL for test requests
let URL = "http://localhost:3001";

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Fetch a real product ID from the products API
    let productsResponse = await client.sendRequest({
        url: URL,
        path: "/api/products",
        method: "GET",
        headers: headers
    });
    const products = JSON.parse(productsResponse.responseBody);
    const realProductId = products[0].id;

    // Request Body
    const checkoutPostRequestBody = JSON.stringify({
            "customer": {
                "address": "123 Main St, New York 10001",
                "email": "jane@example.com",
                "name": "Jane Smith"
            },
            "discountCode": "SAVE10",
            "items": [
                {
                    "productId": realProductId,
                    "quantity": 1
                }
            ],
            "paymentMethod": "credit_card"
        })
    
    // Expected Response Body
    const expectedCheckoutPostResponseBody = `{
            "createdAt": "2026-03-05T12:00:00.000Z",
            "customer": {
                "address": "123 Main St, New York 10001",
                "email": "jane@example.com",
                "name": "Jane Smith"
            },
            "discountAmount": 16,
            "discountCode": "SAVE10",
            "id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
            "items": [
                {
                    "name": "Wireless Headphones",
                    "price": 79.99,
                    "productId": "781a9c25-e241-4baa-9440-81d1f647d47e",
                    "quantity": 2,
                    "subtotal": 159.98
                }
            ],
            "paymentMethod": "credit_card",
            "paymentStatus": "success",
            "status": "confirmed",
            "subtotal": 159.98,
            "total": 143.98
        }`
    
    // Execute Request
    let checkoutPostResponse = await client.sendRequest({
        url:URL,
        path:"/api/checkout",
        method:"POST",
        body:checkoutPostRequestBody,
        headers:headers
    });

    // Generated Assertions
    assert.strictEqual(checkoutPostResponse.statusCode, 201, 'status code');
});

