// Generated by Skyramp v1.3.11 on 2026-03-10 19:32:12.019189067 +0000 UTC m=+190.663077059
// Command: skyramp generate integration rest \
// 		--chaining-key response.id \
// 		--framework playwright \
// 		--language javascript \
// 		--output flat_discount_checkout_integration_test.spec.js \
// 		--output-dir /home/runner/work/new-project/new-project/tests \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/new-project/new-project/tests/scenario_flat-discount-checkout.json

// Import of required libraries
const { SkyrampClient, getValue } = require('@skyramp/skyramp');
const { test } = require('@playwright/test');
const assert = require('assert');

// URL for test requests
let URL_localhost = "http://localhost:3001";

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Declaration of variables
    let validate = "FLAT5";

    // Execute Request
    let validateGetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/discounts/validate/{validate}",
        method:"GET",
        pathParams:{"validate": validate}
    });

    // Generated Assertions
    assert.strictEqual(validateGetResponse.statusCode, 200, 'status code');

    // Request Body
    const checkoutPostRequestBody = `{
            "customer": {
                "address": "123 Main St, New York 10001",
                "email": "jane@example.com",
                "name": "Jane Smith"
            },
            "discountCode": "FLAT5",
            "items": [
                {
                    "productId": "a1000000-0000-0000-0000-000000000001",
                    "quantity": 1
                }
            ],
            "paymentMethod": "credit_card"
        }`
    
    // Execute Request
    let checkoutPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/checkout",
        method:"POST",
        body:checkoutPostRequestBody
    });

    // Generated Assertions
    assert.strictEqual(checkoutPostResponse.statusCode, 201, 'status code');
});

