// Generated by Skyramp v1.3.11 on 2026-03-05 19:40:42.882281784 +0000 UTC m=+152.835828022
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language javascript \
// 		--output-dir /home/runner/work/new-project/new-project/tests \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/new-project/new-project/tests/skyramp_traces.json

// Import of required libraries
const { SkyrampClient, getValue, getResponseValue } = require('@skyramp/skyramp');
const { test } = require('@playwright/test');
const assert = require('assert');

// URL for test requests
let URL_accounts = "https://accounts.google.com";
let URL_clients2 = "http://clients2.google.com";
let URL_new_project_azure_five = "https://new-project-azure-five.vercel.app";

test('testIntegration', async () => {
    test.setTimeout(66000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Execute Request
    let listAccountsPostResponse = await client.sendRequest({
        url:URL_accounts,
        path:"/ListAccounts",
        method:"POST",
        queryParams:{
            "gpsia": ["1"],
            "json": ["standard"],
            "laf": ["b64bin"],
            "source": ["ChromiumBrowser"]
        },
        formParams:{" ": ""}
    });

    // Generated Assertions
    assert.strictEqual(listAccountsPostResponse.statusCode, 200, 'status code');

    // Execute Request
    let endpoint1GetResponse = await client.sendRequest({
        url:URL_new_project_azure_five,
        path:"/",
        method:"GET"
    });

    // Generated Assertions
    assert.strictEqual(endpoint1GetResponse.statusCode, 200, 'status code');

    // Execute Request
    let faviconIcoGetResponse = await client.sendRequest({
        url:URL_new_project_azure_five,
        path:"/favicon.ico",
        method:"GET",
        headers:{"Referer": "https://new-project-azure-five.vercel.app/"}
    });

    // Generated Assertions
    assert.strictEqual(faviconIcoGetResponse.statusCode, 200, 'status code');

    // Execute Request
    let productsGetResponse = await client.sendRequest({
        url:URL_new_project_azure_five,
        path:"/api/products",
        method:"GET",
        headers:{"Referer": "https://new-project-azure-five.vercel.app/"}
    });

    // Generated Assertions
    assert.strictEqual(productsGetResponse.statusCode, 200, 'status code');

    // Request Body
    const productsProductsPutRequestBody = `{
            "category": "Footwear",
            "description": "Lightweight and comfortable running shoes",
            "image": "https://placehold.co/300x200?text=Running+Shoes",
            "name": "Running Shoes",
            "price": 100,
            "stock": 30
        }`
    
    // Execute Request
    let productsProductsPutResponse = await client.sendRequest({
        url:URL_new_project_azure_five,
        path:"/api/products/{products}",
        method:"PUT",
        body:productsProductsPutRequestBody,
        headers:{"Referer": "https://new-project-azure-five.vercel.app/"},
        pathParams:{"products": getResponseValue(productsGetResponse, "1.id")},
        dataOverride:{
            "category": getResponseValue(productsGetResponse, "1.category"),
            "description": getResponseValue(productsGetResponse, "1.description"),
            "image": getResponseValue(productsGetResponse, "1.image"),
            "name": getResponseValue(productsGetResponse, "1.name"),
            "stock": getResponseValue(productsGetResponse, "1.stock")
        }
    });

    // Generated Assertions
    assert.strictEqual(productsProductsPutResponse.statusCode, 200, 'status code');

    // Execute Request
    let productsGet1Response = await client.sendRequest({
        url:URL_new_project_azure_five,
        path:"/api/products",
        method:"GET",
        headers:{"Referer": "https://new-project-azure-five.vercel.app/"}
    });

    // Generated Assertions
    assert.strictEqual(productsGet1Response.statusCode, 200, 'status code');

    // Execute Request
    let ordersGetResponse = await client.sendRequest({
        url:URL_new_project_azure_five,
        path:"/api/orders",
        method:"GET",
        headers:{"Referer": "https://new-project-azure-five.vercel.app/orders"}
    });

    // Generated Assertions
    assert.strictEqual(ordersGetResponse.statusCode, 200, 'status code');

    // Execute Request
    let faviconIcoGet1Response = await client.sendRequest({
        url:URL_new_project_azure_five,
        path:"/favicon.ico",
        method:"GET",
        headers:{"Referer": "https://new-project-azure-five.vercel.app/checkout"}
    });

    // Generated Assertions
    assert.strictEqual(faviconIcoGet1Response.statusCode, 200, 'status code');

    // Request Body
    const checkoutPostRequestBody = `{
            "customer": {
                "address": ",  ",
                "email": "nk@skyramp.dev",
                "name": "NK"
            },
            "items": [
                {
                    "productId": "6a67fc7a-9292-4623-9581-1a4bd3b69e39",
                    "quantity": 1
                },
                {
                    "productId": "eb6411de-1738-44cd-b174-06d4f602cbe8",
                    "quantity": 1
                }
            ],
            "paymentMethod": "credit_card"
        }`
    
    // Execute Request
    let checkoutPostResponse = await client.sendRequest({
        url:URL_new_project_azure_five,
        path:"/api/checkout",
        method:"POST",
        body:checkoutPostRequestBody,
        headers:{"Referer": "https://new-project-azure-five.vercel.app/checkout"},
        dataOverride:{
            "items": [
                {
                    "productId": getResponseValue(productsGetResponse, "0.id"),
                    "quantity": 1
                },
                {
                    "productId": getResponseValue(productsGetResponse, "1.id"),
                    "quantity": 1
                }
            ]
        }
    });

    // Generated Assertions
    assert.strictEqual(checkoutPostResponse.statusCode, 201, 'status code');

    // Execute Request
    let ordersOrdersGetResponse = await client.sendRequest({
        url:URL_new_project_azure_five,
        path:"/api/orders/{orders}",
        method:"GET",
        headers:{"Referer": "https://new-project-azure-five.vercel.app/orders/d142f8e2-ed0d-410f-9419-1e9a9ac97c1d"},
        pathParams:{"orders": getResponseValue(checkoutPostResponse, "id")}
    });

    // Generated Assertions
    assert.strictEqual(ordersOrdersGetResponse.statusCode, 200, 'status code');

    // Execute Request
    let faviconIcoGet2Response = await client.sendRequest({
        url:URL_new_project_azure_five,
        path:"/favicon.ico",
        method:"GET",
        headers:{"Referer": "https://new-project-azure-five.vercel.app/orders/d142f8e2-ed0d-410f-9419-1e9a9ac97c1d"}
    });

    // Generated Assertions
    assert.strictEqual(faviconIcoGet2Response.statusCode, 200, 'status code');
});

