// Generated by Skyramp v1.3.13 on 2026-03-16 21:31:47.992439455 +0000 UTC m=+259.242577549
// Command: skyramp generate contract rest http://localhost:3001/api/orders \
// 		--api-schema /home/runner/work/new-project/new-project/openapi.yaml \
// 		--framework playwright \
// 		--language javascript \
// 		--method GET \
// 		--output orders_pagination_contract_test.spec.js \
// 		--output-dir /home/runner/work/new-project/new-project/tests \
// 		--overwrite \
// 		--provider \
// 		--response-status-code 200 \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
const { SkyrampClient, checkSchema, getBaseUrl, getResponseValue } = require('@skyramp/skyramp');
const { test } = require('@playwright/test');
const assert = require('assert');

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3001");

// contract test for /api/orders GET
test('testOrdersGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Expected Response Body
    const expectedOrdersGetResponseBody = `[
        {
            "createdAt": "2026-03-05T12:00:00.000Z",
            "customer": {
                "address": "123 Main St, New York 10001",
                "email": "jane@example.com",
                "name": "Jane Smith"
            },
            "discountAmount": 16,
            "discountCode": "SAVE10",
            "id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
            "items": [
                {
                    "name": "Wireless Headphones",
                    "price": 79.99,
                    "productId": "201b1f01-7b24-452b-9acb-95aa8fb1a516",
                    "quantity": 2,
                    "subtotal": 159.98
                }
            ],
            "paymentMethod": "credit_card",
            "paymentStatus": "success",
            "status": "confirmed",
            "subtotal": 159.98,
            "total": 143.98
        }
    ]`;

    // Execute Request
    const ordersGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/orders",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    assert.strictEqual(ordersGetResponse.statusCode, 200, 'status code');
    assert.ok(checkSchema(ordersGetResponse, expectedOrdersGetResponseBody), 'schema should match');
    assert.notStrictEqual(getResponseValue(ordersGetResponse, "0.createdAt"), null, 'value should not be null');
    assert.notStrictEqual(getResponseValue(ordersGetResponse, "0.customer.address"), null, 'value should not be null');
    assert.notStrictEqual(getResponseValue(ordersGetResponse, "0.customer.email"), null, 'value should not be null');
});
