// Generated by Skyramp v1.3.11 on 2026-03-05 19:40:52.947201637 +0000 UTC m=+162.900747875
// Command: skyramp generate smoke rest https://new-project-azure-five.vercel.app/api/orders \
// 		--api-schema /home/runner/work/new-project/new-project/openapi.yaml \
// 		--framework playwright \
// 		--language javascript \
// 		--method GET \
// 		--output orders_GET_smoke_test.spec.js \
// 		--output-dir /home/runner/work/new-project/new-project/tests \
// 		--overwrite \
// 		--runtime local

// Import of required libraries
const { SkyrampClient } = require('@skyramp/skyramp');
const { test } = require('@playwright/test');
const assert = require('assert');

// URL for test requests
let URL = "https://new-project-azure-five.vercel.app";

// smoke test for /api/orders GET
test('testOrdersGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    const ordersGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/orders",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    assert.strictEqual(ordersGetResponse.statusCode, 200, 'status code');
});
