// Generated by Skyramp v1.3.11 on 2026-03-05 19:41:00.9549396 +0000 UTC m=+170.908485838
// Command: skyramp generate fuzz rest https://new-project-azure-five.vercel.app/api/products \
// 		--api-schema /home/runner/work/new-project/new-project/openapi.yaml \
// 		--framework playwright \
// 		--language javascript \
// 		--method POST \
// 		--output products_POST_fuzz_test.spec.js \
// 		--output-dir /home/runner/work/new-project/new-project/tests \
// 		--overwrite \
// 		--runtime local

// Import of required libraries
const { SkyrampClient, getValue, iterate } = require('@skyramp/skyramp');
const { test } = require('@playwright/test');
const assert = require('assert');

// URL for test requests
let URL = "https://new-project-azure-five.vercel.app";

// fuzz test for /api/products POST
test('testProductsPost', async () => {
    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const productsPostRequestBody = `{
            "category": "Electronics",
            "description": "High-quality noise-cancelling headphones",
            "image": "https://placehold.co/300x200?text=Headphones",
            "name": "Wireless Headphones",
            "price": 79.99,
            "stock": 50
        }`
    
    // Fuzz strategies
    const productsPostFuzzedBody = {
        "category": "Electronics",
        "description": "High-quality noise-cancelling headphones",
        "image": "https://placehold.co/300x200?text=Headphones",
        "name": "Wireless Headphones",
        "price": 79.99,
        "stock": 50
    };
    // Fuzz status codes
    const expectedProductsPostStatusCode = {
        "category": "400",
        "description": "400",
        "image": "400",
        "name": "400",
        "price": "400",
        "stock": "400"
    };
    // Fuzz status codes for Null values
    const expectedProductsPostNullStatusCode = {
        "category": "400",
        "description": "400",
        "image": "400",
        "name": "400",
        "price": "400",
        "stock": "400"
    };

    // Execute Request
    let productsPostResponse = await client.sendRequest({
        url:URL,
        path:"/api/products",
        method:"POST",
        body:productsPostRequestBody,
        headers:headers,
        expectedCode:"20x"
    });


    for (const key of iterate(productsPostFuzzedBody)) {
        // Execute Request
        productsPostResponse = await client.sendRequest({
            url:URL,
            path:"/api/products",
            method:"POST",
            body:productsPostRequestBody,
            headers:headers,
            dataOverride:{[key]: getValue(productsPostFuzzedBody, key)},
            expectedCode:getValue(expectedProductsPostStatusCode, key),
            description:`Fuzzing request body ${key} to ${getValue(productsPostFuzzedBody, key)}`
        });


        // Execute Request
        productsPostResponse = await client.sendRequest({
            url:URL,
            path:"/api/products",
            method:"POST",
            body:productsPostRequestBody,
            headers:headers,
            dataOverride:{[key]: null},
            expectedCode:getValue(expectedProductsPostNullStatusCode, key),
            description:`Fuzzing request body ${key} to null`
        });
    }


    assert.ok(client.isSuccess(), JSON.stringify(client.getFailedResponses()))
});

