// Generated by Skyramp v1.3.11 on 2026-03-05 19:41:00.9549396 +0000 UTC m=+170.908485838
// Command: skyramp generate fuzz rest https://new-project-azure-five.vercel.app/api/products \
// 		--api-schema /home/runner/work/new-project/new-project/openapi.yaml \
// 		--framework playwright \
// 		--language javascript \
// 		--method POST \
// 		--output products_POST_fuzz_test.spec.js \
// 		--output-dir /home/runner/work/new-project/new-project/tests \
// 		--overwrite \
// 		--runtime local

// Import of required libraries
const { SkyrampClient, getValue, iterate } = require('@skyramp/skyramp');
const { test } = require('@playwright/test');
const assert = require('assert');

// URL for test requests — updated to localhost (was pointing to Vercel deployment)
let URL = "http://localhost:3001";

// fuzz test for /api/products POST
test('testProductsPost', async () => {
    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const productsPostRequestBody = `{
            "category": "Electronics",
            "description": "High-quality noise-cancelling headphones",
            "image": "https://placehold.co/300x200?text=Headphones",
            "name": "Wireless Headphones",
            "price": 79.99,
            "stock": 50
        }`;

    // Fuzz strategies: use invalid values to test boundary conditions
    // Only name and price are required; others (category, description, image, stock) are optional
    const productsPostFuzzedBody = {
        "category": "Electronics",       // optional, any string accepted
        "description": "Test desc",      // optional, any string accepted
        "image": "https://example.com",  // optional, any string accepted
        "name": "Test Product",          // required, any non-empty string accepted
        "price": -1,                     // invalid: negative price still accepted by API (no range check)
        "stock": -1                      // optional, parseInt(-1) = -1 accepted
    };
    // Fuzz status codes: only name and price are required (null triggers 400)
    // Non-null fuzz values for all fields return 20x since backend has no range validation
    const expectedProductsPostStatusCode = {
        "category": "20x",
        "description": "20x",
        "image": "20x",
        "name": "20x",
        "price": "20x",
        "stock": "20x"
    };
    // Fuzz status codes for Null values:
    // - name null → 40x (required: "Name and price are required")
    // - price null → 40x (required: "Name and price are required")
    // - others null → 20x (optional, backend uses defaults)
    const expectedProductsPostNullStatusCode = {
        "category": "20x",
        "description": "20x",
        "image": "20x",
        "name": "40x",
        "price": "40x",
        "stock": "20x"
    };

    // Execute Request
    let productsPostResponse = await client.sendRequest({
        url:URL,
        path:"/api/products",
        method:"POST",
        body:productsPostRequestBody,
        headers:{ ...headers, "Content-Type": "application/json" },
        expectedCode:"20x"
    });


    for (const key of iterate(productsPostFuzzedBody)) {
        // Execute Request
        productsPostResponse = await client.sendRequest({
            url:URL,
            path:"/api/products",
            method:"POST",
            body:productsPostRequestBody,
            headers:{ ...headers, "Content-Type": "application/json" },
            dataOverride:{[key]: getValue(productsPostFuzzedBody, key)},
            expectedCode:getValue(expectedProductsPostStatusCode, key),
            description:`Fuzzing request body ${key} to ${getValue(productsPostFuzzedBody, key)}`
        });


        // Execute Request
        productsPostResponse = await client.sendRequest({
            url:URL,
            path:"/api/products",
            method:"POST",
            body:productsPostRequestBody,
            headers:{ ...headers, "Content-Type": "application/json" },
            dataOverride:{[key]: null},
            expectedCode:getValue(expectedProductsPostNullStatusCode, key),
            description:`Fuzzing request body ${key} to null`
        });
    }


    assert.ok(client.isSuccess(), JSON.stringify(client.getFailedResponses()))
});
