// Generated by Skyramp v1.3.11 on 2026-03-05 19:12:26.197516567 +0000 UTC m=+136.593522333
// Command: skyramp generate smoke rest http://localhost:3001/api/products \
// 		--framework playwright \
// 		--language javascript \
// 		--method GET \
// 		--output-dir /home/runner/work/new-project/new-project/tests \
// 		--overwrite \
// 		--runtime local

// Import of required libraries
const { SkyrampClient, checkStatusCode } = require('@skyramp/skyramp');
const { test } = require('@playwright/test');
const assert = require('assert');

// URL for test requests
let URL = "http://localhost:3001";

// smoke test for /api/products GET
test('testProductsGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    const productsGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/products",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    assert.ok(checkStatusCode(productsGetResponse, "20X"), 'status code should equal 20X');
});
