// Generated by Skyramp v1.3.11 on 2026-03-06 21:19:04.855189223 +0000 UTC m=+172.609953441
// Command: skyramp generate load rest http://localhost:3001/api/products \
// 		--api-schema /home/runner/work/new-project/new-project/openapi.yaml \
// 		--default-duration 5 \
// 		--default-num-threads 1 \
// 		--framework playwright \
// 		--language javascript \
// 		--method POST \
// 		--output reset_products_POST_load_test.spec.js \
// 		--output-dir /home/runner/work/new-project/new-project/tests \
// 		--overwrite \
// 		--runtime local

// Import of required libraries
const { SkyrampClient } = require('@skyramp/skyramp');
const { AsyncScenario, LoadTestConfig } = require('@skyramp/skyramp');const { test } = require('@playwright/test');
const assert = require('assert');

// URL for test requests
let URL = "http://localhost:3001";

let loadTestConfig = new LoadTestConfig({
    loadDuration: 5,
    loadNumThreads: 1
});

test('testProductsPost', async () => {
    test.setTimeout(35000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    const scenario = new AsyncScenario({name: "scenario"});
    // Request Body
    const productsPostRequestBody = `{
            "category": "Electronics",
            "description": "High-quality noise-cancelling headphones",
            "image": "https://placehold.co/300x200?text=Headphones",
            "name": "Wireless Headphones",
            "price": 79.99,
            "stock": 50
        }`
    
    // Add Request to Scenario
    let productsPostResponse = scenario.addAsyncRequest({
        name: "products_POST",
        url: URL,
        path: "/api/products",
        method: "POST",
        body: productsPostRequestBody,
        headers: headers,
        expectedCode: "201"
    });

    const result = await client.sendScenario(scenario, {
            loadTestConfig: loadTestConfig
        });

    const overallStatus = await result.getOverallStatus();
    console.log(JSON.stringify({ "result": overallStatus }, null, 2));
});

