// Generated by Skyramp v1.3.11 on 2026-03-06 21:18:56.237156976 +0000 UTC m=+163.991921184
// Command: skyramp generate integration rest http://localhost:3001/api/products \
// 		--api-schema /home/runner/work/new-project/new-project/openapi.yaml \
// 		--framework playwright \
// 		--language javascript \
// 		--output reset_integration_test.spec.js \
// 		--output-dir /home/runner/work/new-project/new-project/tests \
// 		--overwrite \
// 		--runtime local

// Import of required libraries
const { SkyrampClient, getValue, getResponseValue } = require('@skyramp/skyramp');
const { test } = require('@playwright/test');
const assert = require('assert');

// URL for test requests
let URL = "http://localhost:3001";

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const productsPostRequestBody = `{
            "category": "Electronics",
            "description": "High-quality noise-cancelling headphones",
            "image": "https://placehold.co/300x200?text=Headphones",
            "name": "Wireless Headphones",
            "price": 79.99,
            "stock": 50
        }`
    
    // Execute Request
    let productsPostResponse = await client.sendRequest({
        url:URL,
        path:"/api/products",
        method:"POST",
        body:productsPostRequestBody,
        headers:headers
    });

    // Generated Assertions
    assert.strictEqual(productsPostResponse.statusCode, 201, 'status code');

    let max_retries = 10;
    let sleep_time = 5;
    for (let idx=0 ; idx < max_retries ; idx++) {
        // Execute Request
        let productsIdGetResponse = await client.sendRequest({
            url:URL,
            path:"/api/products/{id}",
            method:"GET",
            headers:headers,
            pathParams:{"id": getResponseValue(productsPostResponse, "id")}
        });

        if (productsIdGetResponse.statusCode == 200) {
            break;
        }

            setTimeout(() => {}, sleep_time * 1000);
    }



    // Request Body
    const productsIdPutRequestBody = `{
            "category": "Electronics",
            "description": "High-quality noise-cancelling headphones",
            "image": "https://placehold.co/300x200?text=Headphones",
            "name": "Wireless Headphones",
            "price": 79.99,
            "stock": 50
        }`
    
    // Execute Request
    let productsIdPutResponse = await client.sendRequest({
        url:URL,
        path:"/api/products/{id}",
        method:"PUT",
        body:productsIdPutRequestBody,
        headers:headers,
        pathParams:{"id": getResponseValue(productsPostResponse, "id")}
    });

    // Generated Assertions
    assert.strictEqual(productsIdPutResponse.statusCode, 200, 'status code');

    // Execute Request
    let productsIdDeleteResponse = await client.sendRequest({
        url:URL,
        path:"/api/products/{id}",
        method:"DELETE",
        headers:headers,
        pathParams:{"id": getResponseValue(productsPostResponse, "id")}
    });

    // Generated Assertions
    assert.strictEqual(productsIdDeleteResponse.statusCode, 200, 'status code');
});

