// Generated by Skyramp v1.3.11 on 2026-03-06 21:18:43.751410027 +0000 UTC m=+151.506174235
// Command: skyramp generate contract rest http://localhost:3001/api/products \
// 		--api-schema /home/runner/work/new-project/new-project/openapi.yaml \
// 		--framework playwright \
// 		--language javascript \
// 		--method POST \
// 		--output reset_products_POST_contract_test.spec.js \
// 		--output-dir /home/runner/work/new-project/new-project/tests \
// 		--overwrite \
// 		--runtime local

// Import of required libraries
const { SkyrampClient, checkSchema, getResponseValue } = require('@skyramp/skyramp');
const { test } = require('@playwright/test');
const assert = require('assert');

// URL for test requests
let URL = "http://localhost:3001";

// contract test for /api/products POST
test('testProductsPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const productsPostRequestBody = `{
        "category": "Electronics",
        "description": "High-quality noise-cancelling headphones",
        "image": "https://placehold.co/300x200?text=Headphones",
        "name": "Wireless Headphones",
        "price": 79.99,
        "stock": 50
    }`;

    // Expected Response Body
    const expectedProductsPostResponseBody = `{
        "category": "Electronics",
        "description": "High-quality noise-cancelling headphones",
        "id": "697e5563-5eed-45db-be7c-b543a102641b",
        "image": "https://placehold.co/300x200?text=Headphones",
        "name": "Wireless Headphones",
        "price": 79.99,
        "stock": 50
    }`;

    // Execute Request
    const productsPostResponse = await client.sendRequest({
        url: URL,
        path: "/api/products",
        method: "POST",
        body: productsPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    assert.strictEqual(productsPostResponse.statusCode, 201, 'status code');
    assert.ok(checkSchema(productsPostResponse, expectedProductsPostResponseBody), 'schema should match');
    assert.notStrictEqual(getResponseValue(productsPostResponse, "category"), null, 'value should not be null');
    assert.notStrictEqual(getResponseValue(productsPostResponse, "description"), null, 'value should not be null');
    assert.notStrictEqual(getResponseValue(productsPostResponse, "id"), null, 'value should not be null');
});
