// Generated by Skyramp v1.3.11 — Contract test for POST /api/products/:id/reviews
// Validates response schema and error handling for review creation

// Import of required libraries
const { SkyrampClient, checkStatusCode } = require('@skyramp/skyramp');
const { test } = require('@playwright/test');
const assert = require('assert');

// URL for test requests
let URL = "http://localhost:3001";

// contract test for /api/products/:id/reviews POST
test('testProductReviewsPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Step 1: GET a valid product ID
    const productsGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/products",
        method: "GET",
        headers: headers
    });
    assert.ok(checkStatusCode(productsGetResponse, "20X"), 'GET /api/products should return 200');
    const products = JSON.parse(productsGetResponse.responseBody);
    assert.ok(Array.isArray(products) && products.length > 0, 'products array should not be empty');
    const productId = products[0].id;

    // Step 2: POST a review for the product
    const reviewRequestBody = JSON.stringify({
        author: "Contract Tester",
        rating: 4,
        comment: "Contract test review"
    });

    const reviewPostResponse = await client.sendRequest({
        url: URL,
        path: `/api/products/${productId}/reviews`,
        method: "POST",
        body: reviewRequestBody,
        headers: { ...headers, "Content-Type": "application/json" }
    });

    // Validate 201 status
    assert.strictEqual(reviewPostResponse.statusCode, 201, 'status code should equal 201');

    // Validate response schema
    const review = JSON.parse(reviewPostResponse.responseBody);
    assert.ok(typeof review.id === 'string', 'review.id should be a string');
    assert.strictEqual(review.productId, productId, 'review.productId should match');
    assert.strictEqual(review.author, 'Contract Tester', 'review.author should match');
    assert.strictEqual(review.rating, 4, 'review.rating should match');
    assert.ok(typeof review.comment === 'string', 'review.comment should be a string');
    assert.ok(typeof review.createdAt === 'string', 'review.createdAt should be a string');

    // Validate error: missing author returns 400
    const missingAuthorResponse = await client.sendRequest({
        url: URL,
        path: `/api/products/${productId}/reviews`,
        method: "POST",
        body: JSON.stringify({ rating: 3 }),
        headers: { ...headers, "Content-Type": "application/json" }
    });
    assert.strictEqual(missingAuthorResponse.statusCode, 400, 'missing author should return 400');

    // Validate error: rating out of range returns 400
    const invalidRatingResponse = await client.sendRequest({
        url: URL,
        path: `/api/products/${productId}/reviews`,
        method: "POST",
        body: JSON.stringify({ author: "Tester", rating: 10 }),
        headers: { ...headers, "Content-Type": "application/json" }
    });
    assert.strictEqual(invalidRatingResponse.statusCode, 400, 'rating out of range should return 400');
});
