// Generated by Skyramp v1.3.11 on 2026-03-05 21:50:34.107255994 +0000 UTC m=+178.324079076
// Command: skyramp generate contract rest http://localhost:3001/api/products/reviews/all \
// 		--framework playwright \
// 		--language javascript \
// 		--method GET \
// 		--output reviews_GET_contract_test.spec.js \
// 		--output-dir /home/runner/work/new-project/new-project/tests \
// 		--overwrite \
// 		--runtime local

// Import of required libraries
const { SkyrampClient, checkStatusCode } = require('@skyramp/skyramp');
const { test } = require('@playwright/test');
const assert = require('assert');

// URL for test requests
let URL = "http://localhost:3001";

// contract test for /api/products/reviews/all GET
test('testAllGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    const allGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/products/reviews/all",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    assert.ok(checkStatusCode(allGetResponse, "20x"), 'status code should equal 20x');
});
