// Generated by Skyramp v1.3.11 — Fuzz test for POST /api/products/:id/reviews
// Tests boundary conditions: missing fields, invalid rating values, malformed data

// Import of required libraries
const { SkyrampClient, getValue, iterate } = require('@skyramp/skyramp');
const { test } = require('@playwright/test');
const assert = require('assert');

// URL for test requests
let URL = "http://localhost:3001";

// fuzz test for /api/products/:id/reviews POST
test('testProductReviewsPost', async () => {
    // Invocation of Skyramp Client
    let client = new SkyrampClient();

    // Definition of authentication header
    const headers = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Step 0: fetch a valid product ID to use in path
    const productsResponse = await client.sendRequest({
        url: URL,
        path: "/api/products",
        method: "GET",
        headers: headers,
        expectedCode: "20x"
    });
    const productId = JSON.parse(productsResponse.responseBody)[0].id;

    // Request Body
    const reviewsPostRequestBody = `{
        "author": "Test User",
        "rating": 5,
        "comment": "Great product!"
    }`;

    // Fuzz strategies
    const reviewsPostFuzzedBody = {
        "author": "0123456789",
        "comment": "0123456789",
        "rating": -10
    };
    // Fuzz status codes: any string is valid for author; comment is optional; rating must be 1-5
    const expectedReviewsPostStatusCode = {
        "author": "20x",  // any non-empty string is valid
        "comment": "20x", // comment is optional
        "rating": "40x"   // -10 is out of range [1,5]
    };
    // Fuzz status codes for Null values: author and rating required; comment optional
    const expectedReviewsPostNullStatusCode = {
        "author": "40x",  // author is required
        "comment": "20x", // comment is optional, defaults to ''
        "rating": "40x"   // rating is required
    };

    // Execute valid request first
    let reviewsPostResponse = await client.sendRequest({
        url: URL,
        path: `/api/products/${productId}/reviews`,
        method: "POST",
        body: reviewsPostRequestBody,
        headers: { ...headers, "Content-Type": "application/json" },
        expectedCode: "20x"
    });

    for (const key of iterate(reviewsPostFuzzedBody)) {
        // Execute Request with fuzzed value
        reviewsPostResponse = await client.sendRequest({
            url: URL,
            path: `/api/products/${productId}/reviews`,
            method: "POST",
            body: reviewsPostRequestBody,
            headers: { ...headers, "Content-Type": "application/json" },
            dataOverride: { [key]: getValue(reviewsPostFuzzedBody, key) },
            expectedCode: getValue(expectedReviewsPostStatusCode, key),
            description: `Fuzzing request body ${key} to ${getValue(reviewsPostFuzzedBody, key)}`
        });

        // Execute Request with null value
        reviewsPostResponse = await client.sendRequest({
            url: URL,
            path: `/api/products/${productId}/reviews`,
            method: "POST",
            body: reviewsPostRequestBody,
            headers: { ...headers, "Content-Type": "application/json" },
            dataOverride: { [key]: null },
            expectedCode: getValue(expectedReviewsPostNullStatusCode, key),
            description: `Fuzzing request body ${key} to null`
        });
    }

    assert.ok(client.isSuccess(), JSON.stringify(client.getFailedResponses()));
});
