// Generated by Skyramp v1.3.11 — Fuzz test for GET /api/products/:id/reviews
// Tests boundary conditions: non-existent IDs, invalid formats, special characters

// Import of required libraries
const { SkyrampClient } = require('@skyramp/skyramp');
const { test } = require('@playwright/test');
const assert = require('assert');

// URL for test requests
let URL = "http://localhost:3001";

// fuzz test for /api/products/:id/reviews GET
test('testProductReviewsGetFuzz', async () => {
    // Invocation of Skyramp Client
    let client = new SkyrampClient();

    // Definition of authentication header
    const headers = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Step 1: Positive case — GET a valid product ID and verify 200
    const productsGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/products",
        method: "GET",
        headers: headers,
        expectedCode: "20x"
    });
    const productId = JSON.parse(productsGetResponse.responseBody)[0].id;

    const validResponse = await client.sendRequest({
        url: URL,
        path: `/api/products/${productId}/reviews`,
        method: "GET",
        headers: headers,
        expectedCode: "20x",
        description: `Valid product ID should return 200`
    });

    // Step 2: Fuzz with invalid IDs — all should return 404
    const invalidIds = [
        "00000000-0000-0000-0000-000000000000",  // non-existent UUID
        "not-a-uuid",                              // invalid format
        "'; DROP TABLE products; --",              // SQL injection
        "a".repeat(200),                           // very long string
        "<script>alert(1)</script>",               // XSS attempt
        "null",                                    // string null
        "undefined"                                // string undefined
    ];

    for (const invalidId of invalidIds) {
        await client.sendRequest({
            url: URL,
            path: `/api/products/${encodeURIComponent(invalidId)}/reviews`,
            method: "GET",
            headers: headers,
            expectedCode: "40x",
            description: `Invalid ID "${invalidId.substring(0, 30)}" should return 4xx`
        });
    }

    assert.ok(client.isSuccess(), JSON.stringify(client.getFailedResponses()));
});
