// Generated by Skyramp v1.3.11 — Integration test for GET/POST /api/products/:id/reviews
// Tests the full per-product reviews workflow: fetch reviews, create review, verify it appears

// Import of required libraries
const { SkyrampClient } = require('@skyramp/skyramp');
const { test } = require('@playwright/test');
const assert = require('assert');

// URL for test requests
let URL = "http://localhost:3001";

test('testProductReviewsIntegration', async () => {
    test.setTimeout(30000);

    // Invocation of Skyramp Client
    let client = new SkyrampClient();

    // Definition of authentication header
    const headers = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Step 1: GET /api/products — fetch product list and extract first product id
    const productsGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/products",
        method: "GET",
        headers: headers
    });
    assert.strictEqual(productsGetResponse.statusCode, 200, 'GET /api/products status code');
    const products = JSON.parse(productsGetResponse.responseBody);
    assert.ok(Array.isArray(products) && products.length > 0, 'products array should not be empty');
    const productId = products[0].id;

    // Step 2: GET /api/products/:id/reviews — verify initial reviews are returned
    const initialReviewsResponse = await client.sendRequest({
        url: URL,
        path: `/api/products/${productId}/reviews`,
        method: "GET",
        headers: headers
    });
    assert.strictEqual(initialReviewsResponse.statusCode, 200, 'GET /api/products/:id/reviews status code');
    const initialReviews = JSON.parse(initialReviewsResponse.responseBody);
    assert.ok(Array.isArray(initialReviews), 'initial reviews should be an array');

    // Step 3: POST /api/products/:id/reviews — create a new review
    const reviewRequestBody = JSON.stringify({
        author: "Integration Tester",
        rating: 5,
        comment: "Integration test review — verify end-to-end review flow"
    });
    const reviewPostResponse = await client.sendRequest({
        url: URL,
        path: `/api/products/${productId}/reviews`,
        method: "POST",
        body: reviewRequestBody,
        headers: { ...headers, "Content-Type": "application/json" }
    });
    assert.strictEqual(reviewPostResponse.statusCode, 201, 'POST /api/products/:id/reviews status code');
    const createdReview = JSON.parse(reviewPostResponse.responseBody);
    assert.ok(createdReview.id, 'created review should have an id');
    assert.strictEqual(createdReview.productId, productId, 'review productId should match');
    assert.strictEqual(createdReview.author, 'Integration Tester', 'author should match');
    assert.strictEqual(createdReview.rating, 5, 'rating should match');

    // Step 4: GET /api/products/:id/reviews again — verify the new review appears
    const updatedReviewsResponse = await client.sendRequest({
        url: URL,
        path: `/api/products/${productId}/reviews`,
        method: "GET",
        headers: headers
    });
    assert.strictEqual(updatedReviewsResponse.statusCode, 200, 'updated GET reviews status code');
    const updatedReviews = JSON.parse(updatedReviewsResponse.responseBody);
    assert.ok(Array.isArray(updatedReviews), 'updated reviews should be an array');
    assert.ok(updatedReviews.length > initialReviews.length, 'review count should have increased');
    const foundReview = updatedReviews.some(r => r.id === createdReview.id);
    assert.ok(foundReview, 'created review should appear in the product reviews list');
});
