// Generated by Skyramp v1.3.11 on 2026-03-05 22:13:03.622589149 +0000 UTC m=+259.241778739
// Command: skyramp generate load rest http://localhost:3001/api/products/reviews/all \
// 		--default-duration 5 \
// 		--default-num-threads 1 \
// 		--framework playwright \
// 		--language javascript \
// 		--method GET \
// 		--output reviews_id_GET_load_test.spec.js \
// 		--output-dir /home/runner/work/new-project/new-project/tests \
// 		--overwrite \
// 		--runtime local

// Import of required libraries
const { SkyrampClient, checkStatusCode } = require('@skyramp/skyramp');
const { AsyncScenario, LoadTestConfig } = require('@skyramp/skyramp');const { test } = require('@playwright/test');
const assert = require('assert');

// URL for test requests
let URL = "http://localhost:3001";

let loadTestConfig = new LoadTestConfig({
    loadDuration: 5,
    loadNumThreads: 1
});

test('testAllGet', async () => {
    test.setTimeout(35000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    const scenario = new AsyncScenario({name: "scenario"});
    // Add Request to Scenario
    let allGetResponse = scenario.addAsyncRequest({
        name: "all_GET",
        url: URL,
        path: "/api/products/reviews/all",
        method: "GET",
        headers: headers,
        expectedCode: "20x"
    });

    const result = await client.sendScenario(scenario, {
            loadTestConfig: loadTestConfig
        });

    const overallStatus = await result.getOverallStatus();
    console.log(JSON.stringify({ "result": overallStatus }, null, 2));
});

