// Generated by Skyramp v1.3.11 — Integration test for Reviews API
// Tests the full reviews workflow: create review, fetch by product, fetch all

// Import of required libraries
const { SkyrampClient, getResponseValue } = require('@skyramp/skyramp');
const { test } = require('@playwright/test');
const assert = require('assert');

// URL for test requests
let URL = "http://localhost:3001";

test('testIntegration', async () => {
    test.setTimeout(30000);

    // Invocation of Skyramp Client
    let client = new SkyrampClient();

    // Definition of authentication header
    const headers = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Step 1: GET /api/products — fetch product list and extract first product id
    const productsGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/products",
        method: "GET",
        headers: headers
    });
    assert.strictEqual(productsGetResponse.statusCode, 200, 'GET /api/products status code');
    const productId = JSON.parse(productsGetResponse.responseBody)[0].id;
    assert.ok(productId, 'should have a valid product id');

    // Step 2: POST /api/products/{id}/reviews — create a review
    const reviewRequestBody = JSON.stringify({
        author: "Integration Tester",
        rating: 4,
        comment: "Integration test review — verify end-to-end review flow"
    });
    const reviewPostResponse = await client.sendRequest({
        url: URL,
        path: `/api/products/${productId}/reviews`,
        method: "POST",
        body: reviewRequestBody,
        headers: { ...headers, "Content-Type": "application/json" }
    });
    assert.strictEqual(reviewPostResponse.statusCode, 201, 'POST /api/products/{id}/reviews status code');
    const createdReview = JSON.parse(reviewPostResponse.responseBody);
    assert.ok(createdReview.id, 'created review should have an id');
    assert.strictEqual(createdReview.author, 'Integration Tester', 'author should match');
    assert.strictEqual(createdReview.rating, 4, 'rating should match');

    // Step 3: GET /api/products/{id}/reviews — verify the review appears for the product
    const productReviewsGetResponse = await client.sendRequest({
        url: URL,
        path: `/api/products/${productId}/reviews`,
        method: "GET",
        headers: headers
    });
    assert.strictEqual(productReviewsGetResponse.statusCode, 200, 'GET /api/products/{id}/reviews status code');
    const productReviews = JSON.parse(productReviewsGetResponse.responseBody);
    assert.ok(Array.isArray(productReviews), 'product reviews should be an array');
    const foundInProduct = productReviews.some(r => r.id === createdReview.id);
    assert.ok(foundInProduct, 'created review should appear in product reviews');

    // Step 4: GET /api/products/reviews/all — verify the review appears globally
    const allReviewsGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/products/reviews/all",
        method: "GET",
        headers: headers
    });
    assert.strictEqual(allReviewsGetResponse.statusCode, 200, 'GET /api/products/reviews/all status code');
    const allReviews = JSON.parse(allReviewsGetResponse.responseBody);
    assert.ok(Array.isArray(allReviews), 'all reviews should be an array');
    const foundInAll = allReviews.some(r => r.id === createdReview.id);
    assert.ok(foundInAll, 'created review should appear in all reviews');
});
