// Generated by Skyramp v1.3.11 — Smoke test for GET /api/products/:id/reviews
// Verifies the endpoint is reachable and returns a valid response for a known product

// Import of required libraries
const { SkyrampClient, checkStatusCode } = require('@skyramp/skyramp');
const { test } = require('@playwright/test');
const assert = require('assert');

// URL for test requests
let URL = "http://localhost:3001";

// smoke test for /api/products/:id/reviews GET
test('testProductReviewsGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Step 1: GET a valid product ID from /api/products
    const productsGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/products",
        method: "GET",
        headers: headers
    });
    assert.ok(checkStatusCode(productsGetResponse, "20X"), 'GET /api/products should return 200');
    const products = JSON.parse(productsGetResponse.responseBody);
    assert.ok(Array.isArray(products) && products.length > 0, 'products array should not be empty');
    const productId = products[0].id;

    // Step 2: GET /api/products/:id/reviews using the product ID
    const reviewsGetResponse = await client.sendRequest({
        url: URL,
        path: `/api/products/${productId}/reviews`,
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    assert.ok(checkStatusCode(reviewsGetResponse, "20X"), 'status code should equal 20X');
    const reviews = JSON.parse(reviewsGetResponse.responseBody);
    assert.ok(Array.isArray(reviews), 'response should be an array');
});
