// Generated by Skyramp v1.3.13 on 2026-03-16 21:57:41.783093612 +0000 UTC m=+112.235685211
// Command: skyramp generate ui rest \
// 		--exclude clients2.google.com,accounts.google.com \
// 		--framework playwright \
// 		--language javascript \
// 		--output ui_flow_ui_test.spec.js \
// 		--output-dir /home/runner/work/new-project/new-project/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/new-project/new-project/tests/ui-flow.zip \
// 		--provider \
// 		--skipProvisionParents

// Import of required libraries
const { expect, getValue, newSkyrampPlaywrightPage } = require('@skyramp/skyramp');
const { test } = require('@playwright/test');
const assert = require('assert');

const pageTimeout = 15000;

test.use({
    storageState: '/Users/nkumar0101/Desktop/new-project/tests/skyramp_session_storage.json',
});

test('testUi', async ({ page }) => {
    test.setTimeout(178000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("https://new-project-git-nk-testbot-nkumar0101s-projects.vercel.app/");
    await page.getByTestId("demo-admin-btn").click();
    await page.getByTestId("login-submit-btn").click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByTestId("edit-product-btn-wireless-headphones").click();
    await page.getByTestId("product-form-stock").click();

    const playwrightRequest0 = {"stock": 23};

    await page.getByTestId("product-form-stock").fill(getValue(playwrightRequest0, "stock").toString());
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/products/**");
    await page.getByTestId("product-form-submit").click();
    const response0 = await responsePromise0;

    await expect(page.getByTestId("product-stock-wireless-headphones")).toContainText("23 in stock");
    await page.getByTestId("add-to-cart-btn-wireless-headphones").click();
    await page.getByTestId("add-to-cart-btn-leather-wallet").click();
    await page.getByTestId("delete-product-btn-yoga-mat").click();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise1 = page.waitForResponse("**/api/products/**");
    await page.getByTestId("delete-confirm-ok").click();
    const response1 = await responsePromise1;

    await page.getByTestId("nav-cart").click();
    await page.getByTestId("proceed-to-checkout-btn").click();
    await page.getByTestId("checkout-name").click();

    const playwrightRequest1 = {"customer": {
            "email": "nk@skyramp.dev",
            "name": "N K"
        }};

    await page.getByTestId("checkout-name").fill(getValue(playwrightRequest1, "customer.name"));
    await page.locator("div").filter({ hasText: /^$/ }).click();
    await page.getByTestId("checkout-email").fill(getValue(playwrightRequest1, "customer.email"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise2 = page.waitForResponse("**/api/checkout**");
    await page.getByTestId("place-order-btn").click();
    const response2 = await responsePromise2;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByTestId("view-order-btn").click();
    await expect(page.getByTestId("order-detail-customer-email")).toContainText("nk@skyramp.dev");
    await page.getByTestId("logout-btn").click();
});
