// Generated by Skyramp v1.3.11 on 2026-03-05 19:40:38.336542816 +0000 UTC m=+148.290089054
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language javascript \
// 		--output-dir /home/runner/work/new-project/new-project/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/new-project/new-project/tests/skyramp_playwright.zip

// Import of required libraries
const { expect, getValue, newSkyrampPlaywrightPage } = require('@skyramp/skyramp');
const { test } = require('@playwright/test');
const assert = require('assert');

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(154000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("https://new-project-azure-five.vercel.app/");
    await page.getByRole("button", { name: "Add to Cart" }).first().click();
    await page.getByRole("button", { name: "Edit" }).nth(1).click();
    await page.getByPlaceholder("0.00").click();

    const playwrightRequest0 = {"price": 100};

    await page.getByPlaceholder("0.00").fill(getValue(playwrightRequest0, "price").toString());
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/products/**");
    await page.getByRole("button", { name: "Save Changes" }).click();
    const response0 = await responsePromise0;

    await expect(page.getByRole("main")).toContainText("$100.00");
    await page.getByRole("button", { name: "Add to Cart" }).nth(2).click();
    await page.getByRole("link", { name: "Orders" }).click();
    await page.getByRole("link", { name: "Cart" }).click();
    await page.getByRole("button", { name: "Proceed to Checkout" }).click();
    await page.getByRole("textbox", { name: "Jane Smith" }).click();

    const playwrightRequest1 = {"customer": {
            "email": "nk@skyramp.dev",
            "name": "NK"
        }};

    await page.getByRole("textbox", { name: "Jane Smith" }).fill(getValue(playwrightRequest1, "customer.name"));
    await page.getByRole("textbox", { name: "jane@example.com" }).click();
    await page.getByRole("textbox", { name: "jane@example.com" }).fill(getValue(playwrightRequest1, "customer.email"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise1 = page.waitForResponse("**/api/checkout**");
    await page.getByRole("button", { name: "Place Order · $" }).click();
    const response1 = await responsePromise1;

    await page.getByRole("button", { name: "View Order" }).click();
    await expect(page.getByRole("main")).toContainText("nk@skyramp.dev");
});
