// Generated by Skyramp v1.3.13 on 2026-03-16 21:13:32.701278714 +0000 UTC m=+234.101464843
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language javascript \
// 		--output user_checkout_order_isolation_integration_test.spec.js \
// 		--output-dir /home/runner/work/new-project/new-project/tests \
// 		--overwrite \
// 		--provider \
// 		--runtime local \
// 		--skipProvisionParents \
// 		--trace /home/runner/work/new-project/new-project/tests/scenario_user-checkout-order-isolation.json

// Import of required libraries
const { SkyrampClient, getBaseUrl, getValue, getResponseValue } = require('@skyramp/skyramp');
const { test } = require('@playwright/test');
const assert = require('assert');

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3001");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const loginPostRequestBody = `{
            "email": "admin@shopeasy.com",
            "password": "password123"
        }`
    
    // Execute Request
    let loginPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/auth/login",
        method:"POST",
        body:loginPostRequestBody,
        headers:headers
    });

    // Generated Assertions
    assert.strictEqual(loginPostResponse.statusCode, 200, 'status code');

    // Request Body
    const checkoutPostRequestBody = `{
            "customer": {
                "address": "123 Main St, New York 10001",
                "email": "admin@shopeasy.com",
                "name": "Admin User"
            },
            "items": [
                {
                    "productId": "a1000000-0000-0000-0000-000000000001",
                    "quantity": 1
                }
            ],
            "paymentMethod": "credit_card"
        }`
    
    // Execute Request
    let checkoutPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/checkout",
        method:"POST",
        body:checkoutPostRequestBody,
        headers:headers,
        dataOverride:{"customer.name": getResponseValue(loginPostResponse, "user.name")}
    });

    // Generated Assertions
    assert.strictEqual(checkoutPostResponse.statusCode, 201, 'status code');

    // Execute Request
    let ordersGetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/orders",
        method:"GET",
        headers:headers
    });

    // Generated Assertions
    assert.strictEqual(ordersGetResponse.statusCode, 200, 'status code');
});

